services:

  backendapp:
    build: .
    container_name: backendapp-compose

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/taskdevops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Arya@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 60000

    depends_on:
      - mysqldbb

  mysqldbb:
    image: mysql:8
    container_name: mysqldbb

    environment:
      MYSQL_DATABASE: taskdevops
      MYSQL_ROOT_PASSWORD: Arya@123

    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-com
    ports:
     - "80:80"
    depends_on:
     - backendapp

    volumes:
     - /var/jenkins_home/workspace/JenkinsTest/nginx:/etc/nginx/conf.d

volumes:
     mysql-data:
